### ISSUE TITLE
asset search problem

### ISSUE THREAD

**Issue by ftoevw** [grokability/snipe-it#10056]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

it seems that only users of the user group "super user" can use the search function under Assets > list all assets via the serach-input field. A user who does not belong to this group, but has all other rights, cannot use the search/filter function.

### Reproduction steps

1. give a user all rights except super user an login with this user
2.navigate to the menu all assets > list all assets
3.use input field with class "form-control search-input" for filter function
...

### Expected behavior

it is expected that all assets are listed that are stored according to a search term like asset name or asset owner.

### Screenshots

![XAqfCVRXmg](https://user-images.githubusercontent.com/90311883/132474910-c5620e36-5298-452d-8c10-4f7e29f8ece9.png)
![xWcTLp1y2i](https://user-images.githubusercontent.com/90311883/132474915-1d4e372c-f96e-4c80-9752-ab8075c5aac5.png)

### Snipe-IT Version

5.18

### Operating System

Debian

### Web Server

Apache

### PHP Version

7.3

### Operating System

Windows

### Browser

Chrome,Edge,Firefox

**Comment by inietov** [comment]
This appears to be  addressed in commit f9c0eee7c9e7a29279cc0846d8b2bbd98951acce. Try  updating and let us know if that fixed your problem!!

**Comment by ThomasEgli** [comment]
We have the same problem, with a different configuration:

Snipe-IT versionv 5.1.5 build 6055 (gd9d5b4d73)
PHP Version 7.4.20

Adapting the four lines did not help. It should be mentioned that the search in the licenses and users works without any problems. It's just the assets.

**Comment by ThomasEgli** [comment]
Another observation: when searching with "Advanced Search", it works .

**Comment by snipe** [comment]
Upgrade your install to 5.2.0 and let us know if you’re still seeing the issue.

**Comment by ThomasEgli** [comment]
Yes, even after updating to version 5.2.0 the problem still exists.

**Comment by p-mac90** [comment]
Same problem here. 

Snipe-IT Version: 5.2.0
PHP Version: 7.4.3

It's not possible to search for assets in the overview.

**Comment by p-mac90** [comment]
Update to Snipe-IT Version 5.3.0
PHP Version: 7.4.3

Error still the same - even Super user get no search results 

Debug-Mode is enable - hope the screenshot can help
![Bildschirmfoto 2021-11-04 um 12 23 09](https://user-images.githubusercontent.com/40386292/140307038-d28f2a9a-717c-4536-8a50-a5a235dd3c85.jpg)

The search for users or license e.g. works

**Comment by ThomasEgli** [comment]
This can help you to fix this error:
https://github.com/snipe/snipe-it/issues/8971
https://github.com/snipe/snipe-it/issues/8172
