### ISSUE TITLE
Processing CSV import does not complete and results in a 404 Error

### ISSUE THREAD

**Issue by jarrodCoombes** [grokability/snipe-it#12012]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When importing assets from a CSV file, the process task ends with a green "Success" bar and then immediately throws a 404 error (https://assets.mpcsd.org/undefined) and nothing is imported.

### Reproduction steps

1. Upload a CSV
2. Process the CSV, set Import Type to "Assets", then click "Backup before importing," match the fields then click "Import"
3. Wait for the green "Success" bar
4. Get a 404 Error
5. Search for one of the imported assets and realize they are not there.
...

### Expected behavior

It should import the assets and give me some sort of success message. 

### Snipe-IT Version

6.0.5

### Operating System

Ubuntu Server 20.04.5 LTS

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Mac OS

### Browser

Chrome

### Version

106

### Error messages

```shell
Log file does not contain anything of note, here is an example of one creation:


[2022-10-21 12:28:05] production.INFO: ------------- Action Summary ----------------  
[2022-10-21 12:28:05] production.INFO: Custom Key: category  
[2022-10-21 12:28:05] production.INFO: category: Infrastructure - Wireless Access Point  
[2022-10-21 12:28:05] production.INFO: A matching category: Infrastructure - Wireless Access Point already exists  
[2022-10-21 12:28:05] production.INFO: Custom Key: company  
[2022-10-21 12:28:05] production.INFO: company:   
[2022-10-21 12:28:05] production.INFO: Custom Key: location  
[2022-10-21 12:28:05] production.INFO: location: EN-Small Multi  
[2022-10-21 12:28:05] production.INFO: Location EN-Small Multi was created  
[2022-10-21 12:28:05] production.INFO: Custom Key: manufacturer  
[2022-10-21 12:28:05] production.INFO: manufacturer: Extreme Networks  
[2022-10-21 12:28:05] production.INFO: Manufacturer Extreme Networks already exists  
[2022-10-21 12:28:05] production.INFO: Custom Key: status  
[2022-10-21 12:28:05] production.INFO: status: Deployed  
[2022-10-21 12:28:05] production.INFO: A matching Status Deployed already exists  
[2022-10-21 12:28:05] production.INFO: Custom Key: supplier  
[2022-10-21 12:28:05] production.INFO: supplier: AMS.NET  
[2022-10-21 12:28:05] production.INFO: Supplier AMS.NET already exists  
[2022-10-21 12:28:05] production.INFO: Custom Key: department  
[2022-10-21 12:28:05] production.INFO: department:   
[2022-10-21 12:28:05] production.INFO: Custom Key: manage_first_name  
[2022-10-21 12:28:05] production.INFO: manage_first_name:   
[2022-10-21 12:28:05] production.INFO: Custom Key: manage_last_name  
[2022-10-21 12:28:05] production.INFO: manage_last_name:   
[2022-10-21 12:28:05] production.INFO: Custom Key: item name  
[2022-10-21 12:28:05] production.INFO: item name: EN-SMU-AP510C  
[2022-10-21 12:28:05] production.INFO: Custom Key: notes  
[2022-10-21 12:28:05] production.INFO: notes:   
[2022-10-21 12:28:05] production.INFO: Custom Key: order number  
[2022-10-21 12:28:05] production.INFO: order number:   
[2022-10-21 12:28:05] production.INFO: Custom Key: purchase cost  
[2022-10-21 12:28:05] production.INFO: purchase cost:   
[2022-10-21 12:28:05] production.INFO: Custom Key: purchase date  
[2022-10-21 12:28:05] production.INFO: purchase date:   
[2022-10-21 12:28:05] production.INFO: Custom Key: last_audit_date  
[2022-10-21 12:28:05] production.INFO: last_audit_date:   
[2022-10-21 12:28:05] production.INFO: Custom Key: next_audit_date  
[2022-10-21 12:28:05] production.INFO: next_audit_date:   
[2022-10-21 12:28:05] production.INFO: Custom Key: quantity  
[2022-10-21 12:28:05] production.INFO: quantity:   
[2022-10-21 12:28:05] production.INFO: Custom Key: requestable  
[2022-10-21 12:28:05] production.INFO: requestable:   
[2022-10-21 12:28:05] production.INFO: Custom Key: serial number  
[2022-10-21 12:28:05] production.INFO: serial number: 5102103060253  
[2022-10-21 12:28:05] production.INFO: Custom Key: checkout type  
[2022-10-21 12:28:05] production.INFO: checkout type: Location  
[2022-10-21 12:28:05] production.INFO: Custom Key: checkout location  
[2022-10-21 12:28:05] production.INFO: checkout location: EN-Small Multi  
[2022-10-21 12:28:05] production.INFO: Location EN-Small Multi already exists  
[2022-10-21 12:28:05] production.INFO: Custom Key: asset tag  
[2022-10-21 12:28:05] production.INFO: asset tag: 16589  
[2022-10-21 12:28:05] production.INFO: No Matching Asset, Creating a new one  
[2022-10-21 12:28:05] production.INFO: Custom Key: notes  
[2022-10-21 12:28:05] production.INFO: notes:   
[2022-10-21 12:28:05] production.INFO: Custom Key: image  
[2022-10-21 12:28:05] production.INFO: image:   
[2022-10-21 12:28:05] production.INFO: Custom Key: requestable  
[2022-10-21 12:28:05] production.INFO: requestable:   
[2022-10-21 12:28:05] production.INFO: Custom Key: requestable  
[2022-10-21 12:28:05] production.INFO: requestable:   
[2022-10-21 12:28:05] production.INFO: Custom Key: warranty  
[2022-10-21 12:28:05] production.INFO: warranty:   
[2022-10-21 12:28:05] production.INFO: Custom Key: model name  
[2022-10-21 12:28:05] production.INFO: model name: AP510C  
[2022-10-21 12:28:05] production.INFO: Custom Key: model number  
[2022-10-21 12:28:05] production.INFO: model number: AP510C  
[2022-10-21 12:28:05] production.INFO: A matching model already exists, returning it.  
[2022-10-21 12:28:05] production.INFO: Asset EN-SMU-AP510C with serial number 5102103060253 was created  
[2022-10-21 12:28:05] production.INFO: ------------- Action Summary ----------------  

/var/www/snipe-t/vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php#43

            return $this->getRouteForMethods($request, $others);
        }

        throw new NotFoundHttpException;
    }

    /**

php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by snipe** [comment]
Pretty sure this was fixed in later versions. Can you try upgrading?

**Comment by jarrodCoombes** [comment]
I am trying that now, but running in that same damn composer issue with github needing a token.

<details>
  <summary>Upgrade Errors</summary>

--------------------------------------------------------
STEP 8: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

-- Running the app in production mode.
-- We couldn't find a local composer.phar. No worries, trying globally.
Since you are running composer globally, we won't try to update it for you.
If you run into issues with this step, try running `composer self-update` 
before running this updater again

Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Package operations: 0 installs, 58 updates, 2 removals
Cannot create cache directory /var/www/.cache/composer/files/, or directory is not writable. Proceeding without cache
  - Downloading symfony/deprecation-contracts (v2.5.2)
  - Downloading guzzlehttp/psr7 (2.4.0)
  - Downloading guzzlehttp/guzzle (7.4.5)
  - Downloading symfony/polyfill-mbstring (v1.26.0)
  - Downloading symfony/polyfill-php80 (v1.26.0)
  - Downloading symfony/polyfill-ctype (v1.26.0)
  - Downloading symfony/var-dumper (v5.4.9)
  - Downloading symfony/polyfill-php72 (v1.26.0)
  - Downloading symfony/polyfill-intl-normalizer (v1.26.0)
  - Downloading symfony/polyfill-intl-idn (v1.26.0)
  - Downloading symfony/mime (v5.4.10)
  - Downloading symfony/polyfill-php73 (v1.26.0)
  - Downloading symfony/http-foundation (v5.4.10)
  - Downloading symfony/event-dispatcher-contracts (v2.5.2)
  - Downloading symfony/event-dispatcher (v5.4.9)
  - Downloading symfony/error-handler (v5.4.9)
  - Downloading symfony/http-kernel (v5.4.10)
  - Downloading symfony/polyfill-intl-grapheme (v1.26.0)
  - Downloading symfony/string (v5.4.10)
  - Downloading symfony/service-contracts (v2.5.2)
  - Downloading symfony/console (v5.4.10)
  - Downloading symfony/polyfill-iconv (v1.26.0)
  - Downloading symfony/polyfill-php81 (v1.26.0)
  - Downloading symfony/translation-contracts (v2.5.2)
  - Downloading symfony/translation (v5.4.9)
  - Downloading nesbot/carbon (2.59.1)
  - Downloading monolog/monolog (2.7.0)
  - Downloading league/commonmark (2.3.4)
  - Downloading laravel/serializable-closure (v1.2.0)
  - Syncing webmozart/assert (1.11.0) into cache
    Failed to download webmozart/assert from source: Failed to execute git clone --mirror -- 'https://ghp...myv:x-oauth-basic@github.com/webmozarts/assert.git' '/var/www/.cache/composer/vcs/https---github.com-webmozarts-assert.git/'

fatal: could not create leading directories of '/var/www/.cache/composer/vcs/https---github.com-webmozarts-assert.git'

    Now trying to download from dist
  - Downloading webmozart/assert (1.11.0)
  - Downloading laravel/framework (v8.83.22)
  - Downloading arietimmerman/laravel-scim-server (dev-master 9e7a8fd)
  - Downloading barryvdh/laravel-debugbar (v3.7.0)
  - Downloading dompdf/dompdf (v2.0.0)
  - Downloading barryvdh/laravel-dompdf (v2.0.0)
  - Downloading doctrine/annotations (1.13.3)
  - Syncing doctrine/reflection (1.2.3) into cache
    Failed to download doctrine/reflection from source: Failed to execute git clone --mirror -- 'https://ghp...myv:x-oauth-basic@github.com/doctrine/reflection.git' '/var/www/.cache/composer/vcs/https---github.com-doctrine-reflection.git/'

fatal: could not create leading directories of '/var/www/.cache/composer/vcs/https---github.com-doctrine-reflection.git'

    Now trying to download from dist
  - Downloading doctrine/reflection (1.2.3)
  - Downloading doctrine/cache (1.13.0)
  - Downloading doctrine/dbal (3.3.7)
  - Downloading squizlabs/php_codesniffer (3.7.1)
  - Downloading facade/ignition (2.17.6)
  - Syncing fideloper/proxy (4.4.2) into cache
    Failed to download fideloper/proxy from source: Failed to execute git clone --mirror -- 'https://ghp...myv:x-oauth-basic@github.com/fideloper/TrustedProxy.git' '/var/www/.cache/composer/vcs/https---github.com-fideloper-TrustedProxy.git/'

fatal: could not create leading directories of '/var/www/.cache/composer/vcs/https---github.com-fideloper-TrustedProxy.git'

    Now trying to download from dist
  - Downloading fideloper/proxy (4.4.2)
  - Downloading intervention/image (2.7.2)
  - Downloading paragonie/constant_time_encoding (v2.6.3)
  - Downloading nyholm/psr7 (1.5.1)
  - Downloading league/uri (6.7.1)
  - Downloading firebase/php-jwt (v6.3.0)
  - Downloading nikic/php-parser (v4.14.0)
  - Downloading psy/psysh (v0.11.7)
  - Downloading laravel/ui (v3.4.6)
  - Downloading aws/aws-sdk-php (3.231.12)
  - Syncing league/flysystem-aws-s3-v3 (1.0.30) into cache
    Failed to download league/flysystem-aws-s3-v3 from source: Failed to execute git clone --mirror -- 'https://ghp...myv:x-oauth-basic@github.com/thephpleague/flysystem-aws-s3-v3.git' '/var/www/.cache/composer/vcs/https---github.com-thephpleague-flysystem-aws-s3-v3.git/'

fatal: could not create leading directories of '/var/www/.cache/composer/vcs/https---github.com-thephpleague-flysystem-aws-s3-v3.git'

    Now trying to download from dist
  - Downloading league/flysystem-aws-s3-v3 (1.0.30)
  - Downloading maennchen/zipstream-php (2.2.1)
  - Downloading phpoffice/phpspreadsheet (1.24.1)
  - Downloading livewire/livewire (v2.10.6)
  - Syncing pragmarx/google2fa (v8.0.1) into cache
    Failed to download pragmarx/google2fa from source: Failed to execute git clone --mirror -- 'https://ghp...myv:x-oauth-basic@github.com/antonioribeiro/google2fa.git' '/var/www/.cache/composer/vcs/https---github.com-antonioribeiro-google2fa.git/'

fatal: could not create leading directories of '/var/www/.cache/composer/vcs/https---github.com-antonioribeiro-google2fa.git'

    Now trying to download from dist
  - Downloading pragmarx/google2fa (v8.0.1)
  - Downloading tecnickcom/tc-lib-color (1.14.14)
  - Downloading tecnickcom/tc-lib-barcode (1.17.14)
  0/58 [>---------------------------]   0%
Could not fetch https://api.github.com/repos/guzzle/guzzle/zipball/1dd98b0564cb3f6bd16ce683cb755f94c10fbd82, please review your configured GitHub OAuth token or enter a new one to access private repos
When working with _public_ GitHub repositories only, head to https://github.com/settings/tokens/new?scopes=&description=Composer+on+odo+2022-10-21+1247 to retrieve a token.
This token will have read-only permission for public information only.
When you need to access _private_ GitHub repositories as well, go to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+odo+2022-10-21+1247
Note that such tokens have broad read/write permissions on your behalf, even if not needed by Composer.
Tokens will be stored in plain text in "/var/www/.config/composer/auth.json" for future use by Composer.
For additional information, check https://getcomposer.org/doc/articles/authentication-for-private-packages.md#github-oauth
Token (hidden): _


</details>

**Comment by jarrodCoombes** [comment]
Umm, well it upgrade, even though that error was thrown. Why does Composer always seem to want to a token for github? What have I done wrong here?

At any rate, I am going to re-run the import process and will report back.

**Comment by jarrodCoombes** [comment]
Right, so now I am running 6.0.12, I can upload the CSV file, but there is no longer a "Process" button, just a download and delete button. Not sure where to go from here.

**Comment by jarrodCoombes** [comment]
Update: I managed to fix the upgrade issues. So I am not on 6.0.12 that was upgraded correctly and without error. But the last issue remains, I can upload a CSV, but there is no "Process" button, so it is not clear how to actually import the assets once the CSV is uploaded.

**Comment by snipe** [comment]
The process button would be the blue button with the cloud on it

<img width="1145" alt="Screen Shot 2022-10-21 at 4 50 31 PM" src="https://user-images.githubusercontent.com/197404/197306017-a649ba21-24f5-46fc-87d1-df73363b7f3e.png">

**Comment by jarrodCoombes** [comment]
Huh, that, to me, is a download icon, at least that's what that icon is used for all the other places I've seen it. I thought I had clicked on it and it downloaded the CSV, maybe not. I'll give it a go and see what happens.

**Comment by jarrodCoombes** [comment]
Issue has been resolved. I was able to import. My only feedback on this is that you almost certainly want to change that icon, the cloud with a down arrow like that is almost universally used for download and not import.
