### ISSUE TITLE
Enabling SSL on Docker container

### ISSUE THREAD

**Issue by miguel-bs-01** [grokability/snipe-it#16615]
OS: Ubuntu server 24.04
Snipe version: 8.0.4
Server configuration: Docker

I have an issue with enabling SSL for my snipe instance. Whenever I start my container the first thing it does is disable SSL. This breaks the container by bootlooping since I use SSL Engine in my apache site.

- I've tried enabling SSL by running `a2enmod ssl` from a Dockerfile
- I've tried changing the variable `APP_FORCE_TLS` in my `.env` file to true

All without success. I'm clearly missing something somewhere, but so far I can't figure out where it is. 
If I manually run `a2enmod ssl` inside the Docker container it does work, but I would like to have this automated and not break everytime I run the container again for updates or changes.

**Comment by snipe** [comment]
This was fixed in https://github.com/snipe/snipe-it/pull/16612 and will be in the next tagged release.

**Comment by miguel-bs-01** [comment]
Hi,

The latest tagged release didn't fixed my specific issue. I tried going back to 8.0.3 and 8.0.2, but the problem is also there for me. It keeps disabling ssl for apache everytime the app container starts.

The first thing that I can find in the docker logs is this:
`2025-04-28T08:39:57.018669022Z Module ssl disabled.`
`2025-04-28T08:39:57.018707343Z To activate the new configuration, you need to run:`
`2025-04-28T08:39:57.018712880Z   service apache2 restart`

At some place it's running a `a2dismod ssl` but I can't figure out where this is defined.

**Comment by snipe** [comment]
> The latest tagged release didn't fixed my specific issue. 

The PR I references is not in a tagged release yet.

**Comment by miguel-bs-01** [comment]
Hi,

I've upgraded to 8.1.18 today and we still have the issue. I feel like my problem is unrelated to [#16612](https://github.com/grokability/snipe-it/pull/16612) but is elsewhere in my configuration.

I've added my .env file and docker-compose file for reference. Any ideas why on container start it disables ssl?

[docker-compose.txt](https://github.com/user-attachments/files/21160122/docker-compose.txt)
[snipe_env_file.txt](https://github.com/user-attachments/files/21160123/snipe_env_file.txt)

**Comment by miguel-bs-01** [comment]
Hi,

This issue has been closed, before there was any update. I was wondering if this will still be looked at?

Kind regards,

Miguel

**Comment by snipe** [comment]
It was addressed in April - https://github.com/grokability/snipe-it/issues/16615#issuecomment-2772029961

**Comment by SarunasSabaliauskas** [comment]
How it was addressed? There is no info how to configure ssl on docker compose.
Warning "Module ssl disabled" still shows in logs.

**Comment by uberbrady** [comment]
You _should_ be able to follow the instructions here: https://snipe-it.readme.io/docs/docker#ssl-enabled - copy the key and certificate as specified there, and then add a mapping for port 443 - and then you should have SSL enabled.

<blockquote><img src="https://files.readme.io/e9d890e-small-standalone-transparent-400.png" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/docker#ssl-enabled">Docker</a></strong></div><div>Note very loudly that additional Docker options should be set in the .env file, and they can require a full container rebuild!</div></blockquote>
