### ISSUE TITLE
Web page organization personnel cannot display it

### ISSUE THREAD

**Issue by billese10** [grokability/snipe-it#17400]
Usage environment:

Operating system: Ubuntu 24.04.2 LTS

Docker Service 

images:

snipe/snipe-it:v8.1.18

mariadb:11.8.2

-----
The person shows "No matching records found

<img width="1422" height="293" alt="Image" src="https://github.com/user-attachments/assets/3e54d3df-0f6a-4f36-890f-a8199bd04a5d" />

<img width="1416" height="794" alt="Image" src="https://github.com/user-attachments/assets/a6b269a4-9d4f-4992-a638-1d01b825a7fa" />

Currently, the user organization cannot display it. All the DB information has been checked. It seems that there is no exception when checking the snipe log. How to deal with this situation?

**Comment by snipe** [comment]
I couldn't possibly tell you. It works on the demo, so there's clearly something different between our version and what you're running. Have you tried deliberately inserting a log error (or warning, whatever) into the log to make sure it's writable? 

Usually, the app log tells you the story, but it can only tell the story if it can be written to.

**Comment by billese10** [comment]
Yesterday I tried to check the database data and found that the database data was normal.
I tried to create a user and clicked on the account ID to browse normally.
But I found that when one of my user IDs was opened, a webpage error occurred.
I tried to delete this account from the database and the webpage returned to normal.
Because this abnormal account is quite important, is there any way to fix it?

normal:
<img width="1864" height="777" alt="Image" src="https://github.com/user-attachments/assets/d3581e70-2e9b-4e75-82e7-2459774c1dd6" />
abnormal: (Only User ID 8 will be like this)
<img width="1451" height="566" alt="Image" src="https://github.com/user-attachments/assets/4a0e3018-b7c2-487a-a559-7a3b6022603f" />

**Comment by snipe** [comment]
Hi - sorry you're having trouble. As mentioned in the docs, we need a stack trace and browser console errors in order to help you. 

You can do one of the following, [per the docs](https://snipe-it.readme.io/docs/getting-help#step-3-check-your-app-and-server-logs):

1. Tail the log file and trigger the error, providing us with whatever new information appears in the log file when the error occurs. More information is available [in the documentation](https://snipe-it.readme.io/docs/getting-help). 
2. Provide the contents of your `storage/logs/laravel.log`. Please do not **attach** files, just paste in the log lines that occur when you trigger the error. It's okay if they're long, but re-triggering the error (
3. **For systems NOT exposed to the internet only:** Turn `APP_DEBUG=true` and then trigger the error and show us what's on the screen. Debug mode can expose sensitive information that you do not want the world to see.

https://snipe-it.readme.io/docs/getting-help
https://snipe-it.readme.io/docs/advanced-debugging

If this error is occurring within the web UI, you should also [check your browser console logs](https://snipe-it.readme.io/docs/getting-help#step-2-enable-your-browsers-error-console).

Providing this information will allow us to better isolate whether the issue is a configuration issue or a bug on our end, and will help us answer your questions much more quickly. The more specific you can be, the better we can target the issue for you.

![cd-arrow](https://github.com/user-attachments/assets/f37d80dc-5896-436d-a57f-270c78196afc)


<blockquote><img src="https://files.readme.io/e9d890e-small-standalone-transparent-400.png" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>
<blockquote><img src="https://files.readme.io/e9d890e-small-standalone-transparent-400.png" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/advanced-debugging">Advanced Debugging</a></strong></div><div>Snipe-IT ships with the Laravel Debugbar, an amazing piece of software that lets you introspect much further into the framework and application to troubleshoot issues that may be a little harder to track down. To enable the debugbar, set the following in your .env file, and clear your config cache: ...</div></blockquote>

**Comment by swift2512** [comment]
Is BS_TABLE_STORAGE set to **localStorage** in your .env file?

**Comment by billese10** [comment]
To: snipe

1.Browser error

<img width="734" height="410" alt="Image" src="https://github.com/user-attachments/assets/c00274e0-ebf9-4595-90bb-8f81f49a2f85" />

2.I went into the container storage/logs/laravel.log and there was no information written into his file

3.If I really need your help, can you help me remotely?

**Comment by billese10** [comment]
To swift2512

Yes , There is a setting

<img width="460" height="248" alt="Image" src="https://github.com/user-attachments/assets/bf4cf21a-db89-432b-a037-ed509401400c" />

**Comment by 36864** [comment]
> 2.I went into the container storage/logs/laravel.log and there was no information written into his file

This usually means your web server user doesn't have the appropriate permissions for the log file.
Try following the steps described here: https://snipe-it.readme.io/docs/debugging-permissions#fixing-it

<blockquote><img src="https://files.readme.io/e9d890e-small-standalone-transparent-400.png" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/debugging-permissions#fixing-it">Debugging Server Permissions</a></strong></div><div>❗️ This article refers to web server file system permissions only: It does not address Snipe-IT application permissions. One of the most common issues folks newer to running web servers run into is how to manage the Linux/Windows/etc owners and groups of the Snipe-IT filesystem. As we mention many t...</div></blockquote>

**Comment by billese10** [comment]
To: 36884
I have fixed it according to the URL, but it seems that laravel.log cannot be written, which also causes error 500 to appear directly on the web page.

**Comment by snipe** [comment]
That sounds like you haven’t actually fixed the server permissions tho. Check the file permissions on both the storage directory and the logs directory, and on the log file itself.

**Comment by billese10** [comment]
To snipe
After some research, I found that laravel.log finally had logs written to it. After the modification, the website directly displayed error 500. The log is as follows

root@snipe-backup:~/snipeit# docker exec snipeit-app-1 tail -n 50 /var/www/html/storage/logs/laravel.log
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(706): Illuminate\Foundation\Exceptions\Handler->prepareResponse()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(594): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse()
#17 /var/www/html/app/Exceptions/Handler.php(172): Illuminate\Foundation\Exceptions\Handler->render()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(51): App\Exceptions\Handler->render()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(214): Illuminate\Routing\Pipeline->handleException()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#22 /var/www/html/app/Http/Middleware/NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): App\Http\Middleware\NoSessionStore->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Illuminate\Http\Middleware\TrustProxies->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(127): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Pipeline\Pipeline->then()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#29 /var/www/html/public/index.php(51): Illuminate\Foundation\Http\Kernel->handle()
#30 {main}  
[2025-07-18 12:10:10] production.ERROR: file_put_contents(/var/www/html/storage/framework/views/9065e79a479fcdb86f244f50aa1f572b.php): Failed to open stream: Permission denied {"userId":1,"exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/storage/framework/views/9065e79a479fcdb86f244f50aa1f572b.php): Failed to open stream: Permission denied at /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:204)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(204): file_put_contents()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(196): Illuminate\\Filesystem\\Filesystem->put()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(67): Illuminate\\View\\Compilers\\BladeCompiler->compile()
#5 /var/www/html/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(10): Illuminate\\View\\Engines\\CompilerEngine->get()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(209): Livewire\\Mechanisms\\ExtendBlade\\ExtendedCompilerEngine->get()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(192): Illuminate\\View\\View->getContents()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(161): Illuminate\\View\\View->renderContents()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Response.php(79): Illuminate\\View\\View->render()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(60): Illuminate\\Http\\Response->__construct()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(90): Illuminate\\Routing\\ResponseFactory->make()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(894): Illuminate\\Routing\\ResponseFactory->view()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(815): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(706): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(594): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()
#17 /var/www/html/app/Exceptions/Handler.php(172): Illuminate\\Foundation\\Exceptions\\Handler->render()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(51): App\\Exceptions\\Handler->render()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(214): Illuminate\\Routing\\Pipeline->handleException()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#22 /var/www/html/app/Http/Middleware/NoSessionStore.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): App\\Http\\Middleware\\NoSessionStore->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(127): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#29 /var/www/html/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#30 {main}
"}

**Comment by 36864** [comment]
> production.ERROR: file_put_contents(/var/www/html/storage/framework/views/9065e79a479fcdb86f244f50aa1f572b.php): Failed to open stream: Permission denied

Your permissions are still not right. Your app is unable to write to the storage folder.

**Comment by billese10** [comment]
To 36864

All my services are started with docker, so I changed the permissions to docker:www-data and I can open the web page and collect logs normally, but user id 8 cannot be displayed normally.

laravel.log No error log is written

**Comment by 36864** [comment]
Looking at your error a bit closer, the error message isn't coming from the framework, the error seems to be happening at the web server level.

Can you find the apache error log? Should be at /var/log/apache2/error.log

**Comment by billese10** [comment]
To 36864

I didn't think to check here... I did see the following error log at the bottom: /var/log/apache2/error.log

log:
[Fri Jul 18 04:44:26.921817 2025] [php:error] [pid 141] [client 192.168.231.51:56920] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php on line 1071
[Fri Jul 18 04:44:26.922314 2025] [php:error] [pid 141] [client 192.168.231.51:56920] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/vendor/symfony/error-handler/Error/FatalError.php on line 1
[Mon Jul 21 02:03:33.695893 2025] [php:error] [pid 156] [client 192.168.231.51:49481] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 578, referer: http://10.21.0.243:8000/
[Mon Jul 21 02:03:33.696379 2025] [php:error] [pid 156] [client 192.168.231.51:49481] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/vendor/symfony/error-handler/Error/FatalError.php on line 1, referer: http://10.21.0.243:8000/
[Mon Jul 21 02:03:36.949184 2025] [php:error] [pid 138] [client 192.168.231.51:49496] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php on line 1071
[Mon Jul 21 02:03:36.949766 2025] [php:error] [pid 138] [client 192.168.231.51:49496] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/vendor/symfony/error-handler/Error/FatalError.php on line 1
[Mon Jul 21 02:04:19.718322 2025] [php:error] [pid 17946] [client 192.168.231.51:49495] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/AsPivot.php on line 49
[Mon Jul 21 02:04:19.718884 2025] [php:error] [pid 17946] [client 192.168.231.51:49495] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/vendor/symfony/error-handler/Error/FatalError.php on line 1
[Mon Jul 21 02:07:55.270451 2025] [php:error] [pid 17948] [client 192.168.231.51:49565] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/AsPivot.php on line 49
[Mon Jul 21 02:07:55.271005 2025] [php:error] [pid 17948] [client 192.168.231.51:49565] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/vendor/symfony/error-handler/Error/FatalError.php on line 1
[Mon Jul 21 09:13:16.917486 2025] [php:error] [pid 139] [client 192.168.231.51:59446] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 2325, referer: http://10.21.0.243:8000/
[Mon Jul 21 09:13:16.918020 2025] [php:error] [pid 139] [client 192.168.231.51:59446] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/vendor/symfony/error-handler/Error/FatalError.php on line 1, referer: http://10.21.0.243:8000/

**Comment by billese10** [comment]
Dear All
My problem was solved by changing the php.ini memory size. Thanks for your help

**Comment by 36864** [comment]
I wouldn't call it "solved", more like temporarily fixed. We should look into what was causing that one user to use up so much memory on that page.

**Comment by Kyle-PengZhiWei** [comment]
@billese10 May I ask where you changed the memory size of PHP.ini？I have encountered the same problem as you, Thanks

**Comment by snipe** [comment]
@Kyle-PengZhiWei https://snipe-it.readme.io/docs/changing-php-upload-size

<blockquote><img src="https://files.readme.io/e9d890e-small-standalone-transparent-400.png" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/changing-php-upload-size">Changing PHP upload size</a></strong></div><div>If you need to change the accepted upload size in Snipe-IT, you will need to modify your php.ini file in two places:
; Maximum allowed size for uploaded files.
upload_max_filesize = 25M

; Must be greater than or equal to upload_max_filesize
post_max_size = 30M
Then restart your web server for the c…</div></blockquote>

**Comment by snipe** [comment]
@billese10 Is there anything unusual about that user? Does it have a lot of assets assigned to it, a lot of locations it's the manager of, etc? Is it perhaps its own manager or something else recursive? Since you're only seeing this on that one user, I suspect there's some unsual recursive data going on.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by Kyle-PengZhiWei** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by snipe** [comment]
@Kyle-PengZhiWei  Hi - The maintainers for Snipe-IT speak English as their primary language. Please re-open/re-post this issue comment this ticket in English. We have a lot of tickets to get through, and we try to be really responsive. Having to run everything through a translator slows us down a lot. 

Hopefully we can get you sorted soon :) 

Thanks!
