### ISSUE TITLE
Editing an existing License e.g adding a seat returns a whoops error

### ISSUE THREAD

**Issue by asmiah** [grokability/snipe-it#7717]
Please confirm you have done the following before posting your bug report:

    [NA] I have enabled debug mode

    [ x ] I have read checked the Common Issues page

Describe the bug
When editing an existing License to increase the number of seats this results in:
Whoops, looks like something went wrong. 

To Reproduce

    Go to Licenses
    Click on edit button to edit existing license
    Amend number of seats
    Click on save
    Error appears

Expected behavior
Increase/Decrease the number of seats for that license

Screenshots

Server (please complete the following information):

    Snipe-IT Version
    4.8.0
    OS: [e.g. Ubuntu, CentOS]
    CentOS
    Web Server: [e.g. Apache, IIS]
    Apache
    PHP Version
    7.2

Desktop (please complete the following information):

    Win 10
    Firefox and Edge

Smartphone (please complete the following information):

Error Messages

Error 500 in 

Additional context

    Is this a fresh install or an upgrade?
    Upgrade

    What OS and web server you're running Snipe-IT on
Centos 7 
    What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
 composer install --no-dev --prefer-source
    Include what you've done so far in the installation, and if you got any error messages along the way.
No errors, I had installed Snipe a fresh and then imported a SQL dump of a previous running Snipe version which I had done in the past and then ran a php artisan migrate

    Indicate whether or not you've manually edited any data directly in the database
No

In the network tab in developer mode in Firefox I can see a 500 error

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Scorcher** [comment]
I have 500 error when try to checkout license. There is a stack trace in log files, but i have no time to investigate it. I hope i could spend some time in March to fix it.

**Comment by Scorcher** [comment]
I have investigated the reason of my 500 error and as a result i fixed my patch file.
Now i can't reproduce error while checking out or editing licenses.

**Comment by asmiah** [comment]
Thanks for the update on this @Scorcher - what is the patch file?

**Comment by Scorcher** [comment]
I do some changes in codebase according to my internal workflow in snipe. I made a mistake at those changes and then bravely fixed it.

**Comment by asmiah** [comment]
Hi Can anyone provide any assistance or help on this, this is still an issue for us, I have also upgraded to Snipe version 4.9.1 but the issue still persists.

**Comment by adwilsher** [comment]
Hi, this is also an issue for my team. I am investigating via debug mode, as the laravel.log file does not catch the error. This only occurs when editing a licence. Assets are unaffected, and licences can still be checked out/in.
