### ISSUE TITLE
 Could not bind to LDAP: Strong(er) authentication required

### ISSUE THREAD

**Issue by browntrouser** [grokability/snipe-it#8504]
#### Expected Behavior (or desired behavior if a feature request)

I expect to be able to sync my AD to SNIPE
-----

#### Actual Behavior

 Could not bind to LDAP: Strong(er) authentication required

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? It has been upgraded
- Version of Snipe-IT you're running 4.9.5 BUILD 4482
- Version of PHP you're running 7.3.14
- Version of MySQL/MariaDB you're running 10.4
- What OS and web server you're running Snipe-IT on MS Server 2016
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) GIT

![Doc1](https://user-images.githubusercontent.com/60188283/95484489-86ea2600-095e-11eb-84e1-bbc5172deaf4.png)

THANKS FOR THE HELP

**Comment by uberbrady** [comment]
The latest Golden Master should fix this for you - https://github.com/snipe/snipe-it/releases/tag/v5.0.0-beta-6-GM

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/snipe/snipe-it/releases/tag/v5.0.0-beta-6-GM">Release v5.0.0-beta-6-GM · snipe/snipe-it</a></strong></div><div>New from v5.0.0-beta-5 to v5.0.0-beta-6-GM
This is the golden master for Snipe-IT v5. Primary in this release are some critical fixes for AD interoperability.
IMPORTANT: This version of Snipe-IT re...</div></blockquote>

**Comment by uberbrady** [comment]
We've cleaned up our LDAP setup pretty solidly with the latest v5 release - check out https://github.com/snipe/snipe-it/releases/tag/v5.0.4

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/snipe/snipe-it/releases/tag/v5.0.4">Release v5.0.4 · snipe/snipe-it</a></strong></div><div>New in v5.0.4
This is a bug fix release that should handle some of the issues reported over the past few days.
We'll be hitting them back as quickly as you can throw issues at us, so keep them comi...</div></blockquote>

**Comment by uberbrady** [comment]
You should probably also use `ldaps://` or at least `STARTSSL` to get a more secure connection. Is this working for you?

**Comment by browntrouser** [comment]
Sorry for the REALLY REALLY late response. No, it still does not work unfortunately. I am currently running version 5.0.12

**Comment by uberbrady** [comment]
Maybe you've got to modify your Active Directory server settings? Here's an article that shows some settings that might help - see the "resolution" part.

https://support.forcepoint.com/KBArticle?id=Unable-To-Connect-To-AD-Server-Strong-er-authentication-required

Does that help?

<blockquote><img src="/resource/1584100886000/comunityfavicon" width="48" align="right"></blockquote>

**Comment by browntrouser** [comment]
Thanks for the research. Changing those settings may potentially harm something else so I am going to pass. It is odd though how many other things I have connected to my AD and work fine. :(
