### ISSUE TITLE
v5.0 Branding Issue - "Error: Please check form below for errors" & 404 (Not found) for pictures

### ISSUE THREAD

**Issue by m4zl** [grokability/snipe-it#8531]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

Just upgraded to the latest v5.0 version and cannot change the logo in the branding section. 

Also no images are loaded through the whole application.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Branding'
3. Change Logo and Apply

**Expected behavior**

Logo should be changed

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v5.0
 - OS: Windows
 - Web Server: IIS
 - PHP Version 7.3.9

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [Dell Notebook]
 - OS: [Windows 10 2004]
 - Browser [Microsoft Edge for Business,Internet Explorer]

**Error Messages**

![image](https://user-images.githubusercontent.com/14125915/96548435-2805a480-12ae-11eb-8901-cbc576d93ff5.png)

Also 404 not found are happening as the "wwwroot/snipe-it/public/uploads" folders are empty. 
Under "wwwroot/snipe-it/public/storage" the files can be still found somehow. 

**Additional context**
Upgrade via git and upgrade.php. Everything worked fine before the upgrade.

Thanks for help! 

Edit: Added some new information.

**Comment by GustelDE** [comment]
Same here...
Linux-Docker-Version, updated through Docker-Compose.

![Zwischenablage01](https://user-images.githubusercontent.com/26502186/96556082-d7e00f80-12b8-11eb-974f-7a88cc0817e2.jpg)

**Comment by snipe** [comment]
Try adding 

`CORS_ALLOWED_ORIGINS="*"`

to your .env, and then running `php artisan config:clear`

**Comment by snipe** [comment]
> Also 404 not found are happening as the "wwwroot/snipe-it/public/uploads" folders are empty.
Under "wwwroot/snipe-it/public/storage" the files can be still found somehow.

I'm not sure what you mean here - did you have uploads before, or...?

That dir would only hold publicly accessible uploads (logos, asset models, etc)

**Comment by snipe** [comment]
We shouldn't *need* the CORS_ALLOWED_ORIGIN stuff, since the images would be served from the (literal) same origin - your own web server. But it's worth a try.

**Comment by GustelDE** [comment]
no success with the CORS and config:clear

![01](https://user-images.githubusercontent.com/26502186/96681877-3ddf9c00-1378-11eb-9266-3c37285478e0.jpg)
![Zwischenablage02](https://user-images.githubusercontent.com/26502186/96681881-3f10c900-1378-11eb-927f-07bde62ceff5.jpg)
![03](https://user-images.githubusercontent.com/26502186/96681995-70899480-1378-11eb-9863-a3e0e7524e62.jpg)

**Comment by ISNL-PimP** [comment]
Not sure if this is related, but after upgrading to v5 I also see no images. 
However, after manually doing what the upgrade script told me to (copy everything from `public/uploads` to `storage/app/public` , removing the old dir `public/uploads`, and then rerunning the upgrade script, I am able to upload new branding which then shows up on the interface. 
It does however end up in the _old_ `public/uploads` directory instead of the `storage/app/public` folder.
This seems consistent with what's happening with the images, as the hrefs for the images also point to `/uploads` instead of `/storage` (which is the symlink the upgrader creates to the new storage location).

I fixed it for my install with `ln -s /var/www/snipeit/storage/app/public/ /var/www/snipeit/public/uploads`

**Comment by m4zl** [comment]
> Not sure if this is related, but after upgrading to v5 I also see no images.
> However, after manually doing what the upgrade script told me to (copy everything from `public/uploads` to `storage/app/public` , removing the old dir `public/uploads`, and then rerunning the upgrade script, I am able to upload new branding which then shows up on the interface.
> It does however end up in the _old_ `public/uploads` directory instead of the `storage/app/public` folder.
> This seems consistent with what's happening with the images, as the hrefs for the images also point to `/uploads` instead of `/storage` (which is the symlink the upgrader creates to the new storage location).
> 
> I fixed it for my install with `ln -s /var/www/snipeit/storage/app/public/ /var/www/snipeit/public/uploads`

For me the symlink solution is working right now, but the upload of a new logo is still failing!

To do a symlink in windows with iis configured just use the following:

```cmd
mklink /d C:\inetpub\wwwroot\snipe-it\public\uploads  C:\inetpub\wwwroot\snipe-it\storage\app\public
```

**Comment by m4zl** [comment]
> > Also 404 not found are happening as the "wwwroot/snipe-it/public/uploads" folders are empty.
> > Under "wwwroot/snipe-it/public/storage" the files can be still found somehow.
> 
> I'm not sure what you mean here - did you have uploads before, or...?
> 
> That dir would only hold publicly accessible uploads (logos, asset models, etc)

Sorry my fault. 

I tried to explain the same issue that @ISNL-PimP mentioned. With his symlink workaround I could get it to work that pictures will be shown again, but the upload of a new logo is still failing.

**Comment by snipe** [comment]
So, we spent literally weeks making sure nobody had to do that though. (The symlink stuff I mean). That’s how laravel wants you to do it, but we put in a workaround so that app/storage/public shouldn’t need to be a thing. We didn’t want people to have to mess with symlinks and we didn’t want them to have to move their uploads around.

I’m frustrated to hear folks are having this issue. Give me a bit and we’ll figure this out.

**Comment by snipe** [comment]
I think I see what happened. We had to move heaven and earth to override Laravel's default behavior on uploads, but the upgrade script wasn't updated to reflect that, so it still had the symlink stuff that also moves your files to where Laravel wants them to be. Yay, we're helpful! 

Once I decided I didn't want to use their way of doing things, everything else was updated, but the upgrade.php script never had that part pulled, so it moved your existing files, even though the rest of the system was using the overrides. 

I've pushed out a fix for that in upgrade.php, but you may need to manually move those files back. I'm sorry about that. It was an oversight. As much as we tested, the upgrade script (obviously) didn't get all the QA love it should have. (It works as it was told to, but we changed course on file paths and that didn't get updated.)

To clarify, Laravel (the framework) wants uploads to live in `app/storage/uploads`, but we didn't want to make people shuffle files around (and not everyone uses upgrade.php to upgrade their Snipe-IT installs, so we had no way of guaranteeing files would have been moved manually). The upgrader wasn't updated to reflect that we're overriding that stuff, so it moved your files and created that symlink. Ideally, you should be able to remove that symlink and move your uploads back to `public/uploads` and it *should* work.

**Comment by GustelDE** [comment]
Still the same Error with Docker Version V5.0.1!
 **Error: Please check the form below for errors**

**Comment by ISNL-PimP** [comment]
Thanks @snipe !
After removing the symlink and copying the files back manually, viewing and uploading media works fine.
One sidenote: I had to run the upgrade script twice before the copy/move code disappeared, since it is already running while pulling the new version of itself. On the second run it stayed away from touching the two dirs.

**Comment by snipe** [comment]
@ISNL-PimP so glad to hear that. Again, very sorry for the hassle.

**Comment by GustelDE** [comment]
My problem, regarding image upload and displaying, was solved by this: https://github.com/snipe/snipe-it/issues/8578
