### ISSUE TITLE
LDAP Synced Users with Login Disabled show error 500 instead of not allowing login

### ISSUE THREAD

**Issue by sanjay900** [grokability/snipe-it#8689]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When a user is syncronised from LDAP, and their login is disabled, then if they try to log in, they will be met with a 500 error instead of actually logging in. We encountered this with a user who had delegation disabled, as currently this will mark a user as login disabled.

**To Reproduce**
1. Tick the "This account is sensitive and cannot be delegated" box for a user on active directory
2. Syncronise with AD
3. Attempt to log in as this user

**Expected behavior**
I would expect to just be told that my credentials are incorrect

**Server:**
 - Snipe-IT Version: v5.0.5-pre - build 5457 (master)
 - OS: CentOS 8
 - Web Server: Apache
 - PHP Version: 7.2.24

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 82.0.2

**Error Messages**
```[2020-11-06 10:53:07] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Return value of App\Services\LdapAd::ldapLogin() must be an instance of App\Models\User, null returned in /var/www/html/snipeit/app/Services/LdapAd.php:127
Stack trace:
#0 /var/www/html/snipeit/app/Http/Controllers/Auth/LoginController.php(146): App\Services\LdapAd->ldapLogin('<username>', '<password>')
#1 /var/www/html/snipeit/app/Http/Controllers/Auth/LoginController.php(207): App\Http\Controllers\Auth\LoginController->loginViaLdap(Object(Illuminate\Http\Request))
#2 [internal function]: App\Http\Controllers\Auth\LoginController->login(Object(Illuminate\Http\Request))
#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('login', Array)
#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Auth\LoginController), 'login')
#6 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#7 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#8 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /var/www/html/snipeit/app/Http/Middleware/RedirectIfAuthenticated.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\RedirectIfAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /var/www/html/snipeit/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /var/www/html/snipeit/app/Http/Middleware/CheckForTwoFactor.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForTwoFactor->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /var/www/html/snipeit/app/Http/Middleware/CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /var/www/html/snipeit/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Cors\HandlePreflight->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#53 /var/www/html/snipeit/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#54 {main}
```

**Additional context**
- happened on both a fresh install and an upgrade
- happens on both a docker and a manual installation

**Comment by uberbrady** [comment]
I think this PR, which was merged, should fix this: #8688 - and it looks like that was you that fixed it, @sanjay900 :) 

Thanks again for your contribution! If you run upgrade.php that will put you on the latest `master` which should include your fix.

**Comment by sanjay900** [comment]
I was curious, would this also be a problem with disabled accounts, or was this only triggerable in this exact circumstance?

**Comment by uberbrady** [comment]
It was definitely a similar bug to what we had in 4.x - basically, if you marked an account as Delegation-disabled, they would be considered 'not real accounts' and be prevented from logging in.

If an account were legitimately disabled, it _should_ work correctly, and "deactivate" the accounts, preventing them from being able to log in. I don't know if such an attempted login would generate a 500 though (And 500'ing is not really the correct response here). I wouldn't be surprised if 'regular' disabled accounts also return a 500 on login-attempt similarly :(

**Comment by snipe** [comment]
@uberbrady in talking with you, it sounds like this issue was not actually solved by that PR, correct?

**Comment by uberbrady** [comment]
Yes, I think I was mistaken. My bad :(

**Comment by uberbrady** [comment]
I've tried all sorts of different scenarios and I haven't been able to generate a 500 yet for various weird things - I tried missing firstnames (which will fail validation), disabled users, re-enabling, deleting the User record from the database - no matter what, I can't seem to get a 500-page on login.

**Comment by snipe** [comment]
There is a fix on master/develop now if anyone wants to pull that down and check if it's working now

**Comment by snipe** [comment]
Anybody still having this issue on master? Or am I good to close it?

**Comment by sanjay900** [comment]
i think we should be fine to close this, i could never reproduce it after the original fix myself
